name: Release-Dry-Run

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - name: Go Semantic Release
        uses: go-semantic-release/action@7149b1688a03fa91bc122d93cd8bc3e95d1872b2 # v1.17.0
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-generator-opt: "emojis=true"
          dry: true
